### PR TITLE
libtailscale: EBADF on bad tailscale_listener_close fd

### PR DESCRIPTION
**Pull request by crawshaw**

### CODE REVIEW

**Review by maisem — APPROVED** [review]
Change LGTM but I can't figure out why the tests are failing

**Review by bradfitz — APPROVED** [review]

**Comment by crawshaw** [comment]
looks like the tests aren't failing. was there a flake I missed? (I can try to hunt down a flake if you have a link.)

**Comment by maisem** [comment]
Yeah it was a flake, I reran it.
https://github.com/tailscale/libtailscale/actions/runs/4394888660/attempts/1

**Comment by crawshaw** [comment]
oh that is a weird test flake. I don't see any path through the code that avoids printing for that. I'll keep my eyes open.

**Pull request merged**
